name: superdeclarative_geometry
version: 0.0.1-dev.1
description: First-class support for angles, polar coordinates, and more.
homepage: 
documentation: 

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:

dev_dependencies:
  test: any

  dart_test_matchers:
    git: git@github.com:matthew-carroll/dart_test_matchers.git

  # flutter_test is here for CI, otherwise would not be necessary.
  flutter_test:
    sdk: flutter

