name: superdeclarative_geometry
version: 0.2.0
description: First-class support for angles, polar coordinates, and more.
homepage: https://github.com/matthew-carroll/superdeclarative_geometry

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:


dev_dependencies:
  test: ^1.20.1
  dart_test_matchers: ^0.2.0
