name: superdeclarative_polar_coords
version: 0.0.9-dev.1
description: First-class support for angles, polar coordinates, and related math.
homepage: 
documentation: 

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:

dev_dependencies:
  test: any

  # flutter_test is here for CI, otherwise would not be necessary.
  flutter_test:
    sdk: flutter

